services:
  mango:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ${DATA_DIR_PATH}:/root/mango
      - ${CONFIG_DIR_PATH}:/root/.config/mango
      - ${PLUGINS_DIR_PATH}:/root/mango/plugins
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
